language: node_js
env:
  - NODE_ENV="development" YARN_CACHE_FOLDER=$TRAVIS_BUILD_DIR/.cache/yarn TRAVIS_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
node_js:
  - "14"
cache:
  yarn: true
  directories:
    - node_modules
    - .cache
jobs:
  include:
    - stage: Lint
      script:
        - yarn lint
    - stage: Test
      script:
        - yarn test
