language: node_js
env:
  global:
    - NODE_ENV="development"
    - TRAVIS_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
node_js:
  - "14"
cache:
  npm: true
  directories:
    - node_modules
    - .cache
jobs:
  include:
    - stage: Test
      script:
        - npm run lint
        - npm test
