language: node_js
env:
  global:
    - NODE_ENV="development"
    - YARN_CACHE_FOLDER=$TRAVIS_BUILD_DIR/.cache/yarn
    - TRAVIS_TAG="$(git rev-parse --short ${TRAVIS_COMMIT})"
node_js:
  - "14"
cache:
  yarn: true
  directories:
    - node_modules
    - .cache
jobs:
  include:
    - stage: Test
      script:
        - yarn lint
        - yarn test
