nodeLinker: node-modules
cacheFolder: "./.cache/yarn/cache"
installStatePath: "./.cache/yarn/install-state.gz"
patchFolder: "./.cache/yarn/patches"
globalFolder: "./.cache/yarn/global"
pnpUnpluggedFolder: "./.cache/yarn/unplugged"
virtualFolder: "./.cache/yarn/__virtual__"
