import { ComponentRegistry } from "@koeroesi86/react-reviver";
import {
  Block,
  Document,
  Fragment,
  IconArrowRight,
  IconBag,
  IconCheck,
  IconFlame,
  IconFlower,
  IconFolder,
  IconGithub,
  IconGraduation,
  IconInfo,
  IconMail,
  IconMapPin,
  IconPhone,
  IconRing,
  IconStar,
  Link,
  Page,
  Rail,
  Text
} from "@pdf-components";

const components: ComponentRegistry = {
  "rail": Rail,
  "document": Document,
  "page": Page,
  "block": Block,
  "text": Text,
  "link": Link,
  "fragment": Fragment,
  "icon-arrow-right": IconArrowRight,
  "icon-ring": IconRing,
  "icon-flame": IconFlame,
  "icon-check": IconCheck,
  "icon-bag": IconBag,
  "icon-graduation": IconGraduation,
  "icon-flower": IconFlower,
  "icon-star": IconStar,
  "icon-info": IconInfo,
  "icon-folder": IconFolder,
  "icon-github": IconGithub,
  "icon-mail": IconMail,
  "icon-map-pin": IconMapPin,
  "icon-phone": IconPhone,
};

export default components;
