name: Branch build

on: 
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      - name: Persist cache
        uses: actions/cache@v3
        id: local-dot-cache
        with:
          path: .cache
          key: ${{ runner.os }}-local-dot-cache-${{ hashFiles('**/yarn.lock') }}
      - name: Setup
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - name: Lint
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: Generate PDF
        uses: borales/actions-yarn@v4
        with:
          cmd: start
      - name: PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-result
          path: dist/**/*.pdf
          if-no-files-found: error
          retention-days: 5
