name: Branch build

on: 
  pull_request:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: 'npm'
      - name: Persist cache
        uses: actions/cache@v6
        id: local-dot-cache
        with:
          path: .cache
          key: ${{ runner.os }}-local-dot-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Setup
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Generate PDF
        env:
          PII_PHONE: ${{ secrets.PII_PHONE }}
          PII_EMAIL: ${{ secrets.PII_EMAIL }}
          PII_LOCATION: ${{ secrets.PII_LOCATION }}
        run: npm run start
      - name: PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: pdf-result
          path: dist/**/*.pdf
          if-no-files-found: error
          retention-days: 5
